/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import controllers.presentation.PresentationCtrl;
import controllers.presentation.UserPresentationCtrl;
import java.awt.Color;
import java.awt.event.KeyEvent;

/**
 *
 * @author Marc
 */
public class LoginView extends javax.swing.JPanel {

    PresentationCtrl pCtrl;
    UserPresentationCtrl uiCtrl;

    /**
     * Creates new form Login
     *
     * @param pCtrl control de presentació
     */
    public LoginView(PresentationCtrl pCtrl) {
        this.pCtrl = pCtrl;
        this.uiCtrl = pCtrl.getUserPresentationCtrl();
        initComponents();
    }

    public void setErrorMessage(String s) {
        jLErrorMessage.setText(s);
        pCtrl.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTUserName = new javax.swing.JTextField();
        jPassword = new javax.swing.JPasswordField();
        jBLogin = new javax.swing.JButton();
        jBRegister = new javax.swing.JButton();
        jBGuest = new javax.swing.JButton();
        UserIcon = new javax.swing.JLabel();
        PasIcon = new javax.swing.JLabel();
        jLErrorMessage = new javax.swing.JLabel();

        setBackground(new Color(0,0,0,0));

        jTUserName.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTUserName.setText("Usuari");
        jTUserName.setToolTipText("Usuari");
        jTUserName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTUserNameMouseClicked(evt);
            }
        });

        jPassword.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPassword.setText("jPasswordField1");
        jPassword.setToolTipText("Contrasenya");
        jPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFocusGained(evt);
            }
        });
        jPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordKeyPressed(evt);
            }
        });

        jBLogin.setText("LOGIN");
        jBLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBLoginMouseClicked(evt);
            }
        });

        jBRegister.setText("REGISTRAR");
        jBRegister.setToolTipText("");
        jBRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBRegisterMouseClicked(evt);
            }
        });
        jBRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegisterActionPerformed(evt);
            }
        });

        jBGuest.setText("CONVIDAT");
        jBGuest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBGuestMouseClicked(evt);
            }
        });

        UserIcon.setBackground(new Color(0,0,0,0));
        UserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/userIcon.png"))); // NOI18N

        PasIcon.setBackground(new Color(0,0,0,0));
        PasIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/lock.png"))); // NOI18N

        jLErrorMessage.setBackground(new Color(0,0,0,0));
        jLErrorMessage.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(267, 267, 267)
                            .addComponent(jTUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(UserIcon))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(208, 208, 208)
                                .addComponent(jBRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBGuest, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(PasIcon)))))))
                .addContainerGap(254, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PasIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jLErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jBLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBGuest, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBLoginMouseClicked
        this.login();
    }//GEN-LAST:event_jBLoginMouseClicked

    private void jTUserNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTUserNameMouseClicked
        String user = getUsername();
        if (user != null && user.equals("Usuari")) {
            jTUserName.setText("");
        }
    }//GEN-LAST:event_jTUserNameMouseClicked

    private void jBRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBRegisterMouseClicked
        pCtrl.setPanel("register");
    }//GEN-LAST:event_jBRegisterMouseClicked

    private void jBGuestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBGuestMouseClicked
        pCtrl.setPanel("home");
    }//GEN-LAST:event_jBGuestMouseClicked

    private void jPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFocusGained
        jPassword.setText("");
    }//GEN-LAST:event_jPasswordFocusGained

    private void jPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.login();
        }
    }//GEN-LAST:event_jPasswordKeyPressed

    private void jBRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBRegisterActionPerformed
    
    /**
     * Fa la acció de Login.
     */
    private void login() {
        String user = this.getUsername();
        String password = this.getPassword();
        if (user == null || password == null) {
            this.setErrorMessage("Usuari o contrasenya buits.");
        } else {
            if (!this.uiCtrl.login(user, password)) {
                this.setErrorMessage("Usuari o contrasenya incorrectes.");
            }
        }
    }
    
    private String getUsername() {
        String user = jTUserName.getText();
        if ("".equals(user)) {
            return null;
        }
        return user;
    }

    private String getPassword() {
        String pass = new String(jPassword.getPassword());
        if ("".equals(pass)) {
            return null;
        }
        return pass;
    }


 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PasIcon;
    private javax.swing.JLabel UserIcon;
    private javax.swing.JButton jBGuest;
    private javax.swing.JButton jBLogin;
    private javax.swing.JButton jBRegister;
    private javax.swing.JLabel jLErrorMessage;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jTUserName;
    // End of variables declaration//GEN-END:variables
}
