/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import controllers.presentation.PresentationCtrl;
import controllers.presentation.UserPresentationCtrl;
import controllers.domain.UserDomainCtrl;
import java.awt.Color;
import java.util.Arrays;
/**
 *
 * @author Ferran
 */
public class PassChangeView extends javax.swing.JPanel {
    
    PresentationCtrl pCtrl;
    UserPresentationCtrl uCtrl;
    UserDomainCtrl uDCtrl;
    
    /**
     * Creates new form PassChangeView
     * @param pCtrl control de presentació
     */
    public PassChangeView(PresentationCtrl pCtrl) {
        this.pCtrl = pCtrl;
        this.uCtrl = pCtrl.getUserPresentationCtrl();
         this.uDCtrl = pCtrl.getUserDomainCtrl();
        initComponents();
    }
    
    /**
     * Error de password
     * @param s missatge
     */
    public void setPastPasswordErrorMesage(String s){
        jLPastPasswordError.setText(s);
        pCtrl.repaint();
    }
    
    /**
     * Error del nou password
     * @param s missatge
     */
    public void setNewPassword1ErrorMesage(String s){
        jLNewPassword1Error.setText(s);
        pCtrl.repaint();
    }
    
    /** 
     * Error del nou password
     * @param s missatge
     */
    public void setNewPassword2ErrorMesage(String s){
        jLNewPassword2Error.setText(s);
        pCtrl.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLNewPassword2Error = new javax.swing.JLabel();
        jNewPassword1 = new javax.swing.JPasswordField();
        jNewPassword2 = new javax.swing.JPasswordField();
        jPastPassword = new javax.swing.JPasswordField();
        jLPastPassword = new javax.swing.JLabel();
        jLNewPassword1 = new javax.swing.JLabel();
        jLNewPassword2 = new javax.swing.JLabel();
        jBChangePass = new javax.swing.JButton();
        jBBack = new javax.swing.JButton();
        jLPastPasswordError = new javax.swing.JLabel();
        jLNewPassword1Error = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new Color(0,0,0,0));
        setPreferredSize(new java.awt.Dimension(743, 494));

        jLNewPassword2Error.setForeground(new java.awt.Color(255, 0, 0));

        jNewPassword1.setText("jPasswordField1");
        jNewPassword1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jNewPassword1FocusGained(evt);
            }
        });
        jNewPassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNewPassword1ActionPerformed(evt);
            }
        });
        jNewPassword1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jNewPassword1KeyReleased(evt);
            }
        });

        jNewPassword2.setText("jPasswordField1");
        jNewPassword2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jNewPassword2FocusGained(evt);
            }
        });
        jNewPassword2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jNewPassword2KeyReleased(evt);
            }
        });

        jPastPassword.setText("jPasswordField1");
        jPastPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPastPasswordFocusGained(evt);
            }
        });
        jPastPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPastPasswordKeyReleased(evt);
            }
        });

        jLPastPassword.setForeground(new java.awt.Color(255, 255, 255));
        jLPastPassword.setText("Contrasenya Antiga:");

        jLNewPassword1.setForeground(new java.awt.Color(255, 255, 255));
        jLNewPassword1.setText("Nova Contrasenya:");

        jLNewPassword2.setForeground(new java.awt.Color(255, 255, 255));
        jLNewPassword2.setText("Repeteix Nova Contrasenya:");

        jBChangePass.setText("OK");
        jBChangePass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBChangePassMouseClicked(evt);
            }
        });

        jBBack.setText("ENRRERE");
        jBBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBBackMouseClicked(evt);
            }
        });

        jLPastPasswordError.setForeground(new java.awt.Color(255, 0, 0));

        jLNewPassword1Error.setForeground(new java.awt.Color(255, 0, 0));

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CANVIA CONTRASENYA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 136, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLPastPassword)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLPastPasswordError, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jNewPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jNewPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLNewPassword1)
                            .addComponent(jLNewPassword2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBBack)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBChangePass)))
                        .addComponent(jLNewPassword1Error, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLNewPassword2Error, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPastPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(186, 186, 186))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLPastPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPastPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLPastPasswordError, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLNewPassword1)
                .addGap(4, 4, 4)
                .addComponent(jNewPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLNewPassword1Error, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLNewPassword2)
                .addGap(2, 2, 2)
                .addComponent(jNewPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLNewPassword2Error, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBChangePass, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBBack, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(110, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jNewPassword1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jNewPassword1FocusGained
        jNewPassword1.setText("");
    }//GEN-LAST:event_jNewPassword1FocusGained

    private void jNewPassword1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNewPassword1KeyReleased
        if(correctPassword()){
            setNewPassword2ErrorMesage("");
        }else{
            setNewPassword2ErrorMesage("Les contrasenyes no coincideixen");
        }
    }//GEN-LAST:event_jNewPassword1KeyReleased

    private void jNewPassword2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jNewPassword2FocusGained
        jNewPassword2.setText("");
    }//GEN-LAST:event_jNewPassword2FocusGained

    private void jNewPassword2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNewPassword2KeyReleased
        if(correctPassword()){
            setNewPassword2ErrorMesage("");
        }else{
            setNewPassword2ErrorMesage("Les contrasenyes no coincideixen");
        }
    }//GEN-LAST:event_jNewPassword2KeyReleased

    private void jBChangePassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBChangePassMouseClicked
        String PastPass = this.getPastPassword();
        if (PastPass == null) {
            this.setPastPasswordErrorMesage("El camp està buit.");
            return;
        }
        String Npass1 = this.getNewPassword1();
        if (Npass1 == null) {
            this.setNewPassword1ErrorMesage("El camp està buit.");
            return;
        }
        String Npass2 = this.getNewPassword2();
        if (Npass2 == null) {
            this.setNewPassword2ErrorMesage("El camp està buit.");
            return;
        }
        
        if (PastPass.equals("jPasswordField1")){
            this.setPastPasswordErrorMesage("Nom per defecte no vàlid.");
            return;
        }
        if (!correctPassword()) {
            setNewPassword2ErrorMesage("Les contrasenyes no coincideixen.");
            return;
        }
        if (Npass1.equals("jPasswordField1")){
            setNewPassword2ErrorMesage("Contrasenyes per defecte no vàlides.");
            return;
        }
        String username = uCtrl.getUsername();
        String currentPassword = getPastPassword();
        if (!uDCtrl.correctLoginUser(username, currentPassword)) setPastPasswordErrorMesage("Contrasenya incorrecta");
        else if (!uCtrl.changePassword(username,PastPass,Npass1)){
            this.setPastPasswordErrorMesage("No s'ha pogut canviar la contrasenya. Error desconegut.");
        }
    }//GEN-LAST:event_jBChangePassMouseClicked

    private void jBBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBBackMouseClicked
        pCtrl.setPanel("home");
    }//GEN-LAST:event_jBBackMouseClicked

    private void jPastPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPastPasswordFocusGained
        jPastPassword.setText("");
    }//GEN-LAST:event_jPastPasswordFocusGained

    private void jPastPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPastPasswordKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jPastPasswordKeyReleased

    private void jNewPassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNewPassword1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNewPassword1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBack;
    private javax.swing.JButton jBChangePass;
    private javax.swing.JLabel jLNewPassword1;
    private javax.swing.JLabel jLNewPassword1Error;
    private javax.swing.JLabel jLNewPassword2;
    private javax.swing.JLabel jLNewPassword2Error;
    private javax.swing.JLabel jLPastPassword;
    private javax.swing.JLabel jLPastPasswordError;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jNewPassword1;
    private javax.swing.JPasswordField jNewPassword2;
    private javax.swing.JPasswordField jPastPassword;
    // End of variables declaration//GEN-END:variables
    private String getPastPassword() {
        String PastPass = new String (jPastPassword.getPassword());
        if ("".equals(PastPass)) return null;
        return PastPass;
    }
    
    private String getNewPassword1() {
        String Npass1 = new String(jNewPassword1.getPassword());
        if ("".equals(Npass1)) return null;
        return Npass1;
    }
    
    private String getNewPassword2() {
        String Npass2 = new String(jNewPassword2.getPassword());
        if ("".equals(Npass2)) return null;
        return Npass2;
    }
    
    private boolean correctPassword(){
        return Arrays.toString(jNewPassword1.getPassword()).equals(Arrays.toString(jNewPassword2.getPassword()));
    }
}
