/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import controllers.presentation.GamePresentationCtrl;
import controllers.presentation.PresentationCtrl;
import java.awt.Color;
/**
 *
 * @author Marc
 */
public class PlayView extends javax.swing.JPanel {
    /**
     * Controllers
     */
    private final PresentationCtrl pCtrl;
    private final GamePresentationCtrl giCtrl;
    
    /**
     * Creates new form PlayView
     * @param pCtrl control de presentació
     */
    public PlayView(PresentationCtrl pCtrl) {
        this.pCtrl = pCtrl;
        this.giCtrl = pCtrl.getGamePresentationCtrl();
        initComponents();
        this.jbLoadGame.setEnabled(false);
    }
    
    /**
     * Habilita el carregar partida
     */
    public void enableLoadGame() {
        boolean savedGame = this.giCtrl.savedGame();
        this.jbLoadGame.setEnabled(savedGame);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbSudokuRandom = new javax.swing.JButton();
        jbSudoku = new javax.swing.JButton();
        jbEnrere = new javax.swing.JButton();
        jbLoadGame = new javax.swing.JButton();

        setBackground(new Color(0,0,0,0));

        jbSudokuRandom.setText("SUDOKU ALEATORI");
        jbSudokuRandom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSudokuRandomActionPerformed(evt);
            }
        });

        jbSudoku.setText("SUDOKU");
        jbSudoku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSudokuActionPerformed(evt);
            }
        });

        jbEnrere.setText("ENRERE");
        jbEnrere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEnrereActionPerformed(evt);
            }
        });

        jbLoadGame.setText("CARREGAR PARTIDA");
        jbLoadGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLoadGameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(178, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jbSudokuRandom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbSudoku, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                    .addComponent(jbEnrere, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbLoadGame, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(172, 172, 172))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(jbLoadGame, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbSudokuRandom, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbSudoku, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbEnrere, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbSudokuRandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSudokuRandomActionPerformed
        pCtrl.setGlassPane();
        pCtrl.setPopUpPanel("chooseRandom");
    }//GEN-LAST:event_jbSudokuRandomActionPerformed

    private void jbSudokuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSudokuActionPerformed
        pCtrl.setPanel("chooseBoard");
    }//GEN-LAST:event_jbSudokuActionPerformed

    private void jbEnrereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEnrereActionPerformed
        pCtrl.setPanel("home");
    }//GEN-LAST:event_jbEnrereActionPerformed

    private void jbLoadGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLoadGameActionPerformed
        giCtrl.loadGame();
    }//GEN-LAST:event_jbLoadGameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbEnrere;
    private javax.swing.JButton jbLoadGame;
    private javax.swing.JButton jbSudoku;
    private javax.swing.JButton jbSudokuRandom;
    // End of variables declaration//GEN-END:variables
}
