/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import controllers.presentation.PresentationCtrl;
import controllers.presentation.StatisticsPresentationCtrl;
import java.awt.Color;
import java.util.HashMap;
import java.util.HashSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ferran
 */
public class RecordsView extends javax.swing.JPanel {

    private final PresentationCtrl pCtrl;
    private final StatisticsPresentationCtrl siCtrl;
    
    /**
     * Creates new form RecordsView
     * @param pCtrl control de presentació
     */
    public RecordsView(PresentationCtrl pCtrl) {
        this.pCtrl = pCtrl;
        this.siCtrl = pCtrl.getStatistiscsPresentationCtrl();
        initComponents();
        fillRecords();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTitolLabel = new javax.swing.JLabel();
        jBackButton = new javax.swing.JButton();
        jSeeRankButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jRecordTable = new javax.swing.JTable();

        setBackground(new Color (0,0,0,0));

        jTitolLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jTitolLabel.setForeground(new java.awt.Color(255, 255, 255));
        jTitolLabel.setText("RÈCORDS");

        jBackButton.setText("ENRERE");
        jBackButton.setMinimumSize(new java.awt.Dimension(103, 23));
        jBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackButtonActionPerformed(evt);
            }
        });

        jSeeRankButton.setText("RÀNKING");
        jSeeRankButton.setToolTipText("");
        jSeeRankButton.setMinimumSize(new java.awt.Dimension(103, 23));
        jSeeRankButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSeeRankButtonActionPerformed(evt);
            }
        });

        jRecordTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jRecordTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rècord", "Usuari", "Valor", "Descripció"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jRecordTable.setToolTipText("");
        jRecordTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jRecordTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jRecordTable);
        if (jRecordTable.getColumnModel().getColumnCount() > 0) {
            jRecordTable.getColumnModel().getColumn(0).setMinWidth(100);
            jRecordTable.getColumnModel().getColumn(0).setPreferredWidth(100);
            jRecordTable.getColumnModel().getColumn(0).setMaxWidth(100);
            jRecordTable.getColumnModel().getColumn(1).setResizable(false);
            jRecordTable.getColumnModel().getColumn(2).setMinWidth(100);
            jRecordTable.getColumnModel().getColumn(2).setPreferredWidth(100);
            jRecordTable.getColumnModel().getColumn(2).setMaxWidth(100);
            jRecordTable.getColumnModel().getColumn(3).setMinWidth(300);
            jRecordTable.getColumnModel().getColumn(3).setPreferredWidth(300);
            jRecordTable.getColumnModel().getColumn(3).setMaxWidth(300);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(300, 300, 300)
                .addComponent(jSeeRankButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTitolLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(291, 291, 291))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jTitolLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeeRankButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBackButtonActionPerformed
        // TODO add your handling code here:
        pCtrl.setPanel("home");
    }//GEN-LAST:event_jBackButtonActionPerformed

    private void jSeeRankButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSeeRankButtonActionPerformed
        // TODO go to Ranking
        pCtrl.setPanel("rankingView");
        
    }//GEN-LAST:event_jSeeRankButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBackButton;
    private javax.swing.JTable jRecordTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jSeeRankButton;
    private javax.swing.JLabel jTitolLabel;
    // End of variables declaration//GEN-END:variables

 /**
  * Funció que agafa el Records actuals de la base de dades, mitjançant el controlador,
  * i els posa a la taula de la vista.
  */
    private void fillRecords(){
        DefaultTableModel model = (DefaultTableModel) jRecordTable.getModel();
        HashSet<HashMap<String, Object>> records = siCtrl.getRecords();
        for (HashMap<String, Object> record : records) {
            Object[] fila = new Object[4];
            fila[0] = record.get("type");
            fila[1] = record.get("user");
            fila[2] = record.get("value");
            fila[3] = record.get("description");
            model.addRow(fila);
        }
        jRecordTable.setModel(model);
    };
 
}
