/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import controllers.presentation.PresentationCtrl;
import controllers.presentation.UserPresentationCtrl;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.Arrays;

/**
 *
 * @author Marc
 */
public class RegisterView extends javax.swing.JPanel {

    PresentationCtrl pCtrl;
    UserPresentationCtrl uiCtrl;

    /**
     * Creates new form Register
     *
     * @param pCtrl control de presentació
     */
    public RegisterView(PresentationCtrl pCtrl) {
        this.pCtrl = pCtrl;
        this.uiCtrl = this.pCtrl.getUserPresentationCtrl();
        initComponents();
    }

    public void setUserErrorMesage(String s) {
        jLUserError.setText(s);
        pCtrl.repaint();
    }

    public void setPassword1ErrorMesage(String s) {
        jLPassword1Error.setText(s);
        pCtrl.repaint();
    }

    public void setPassword2ErrorMesage(String s) {
        jLPassword2Error.setText(s);
        pCtrl.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTUserName = new javax.swing.JTextField();
        jPassword1 = new javax.swing.JPasswordField();
        jPassword2 = new javax.swing.JPasswordField();
        jLUserName = new javax.swing.JLabel();
        jLPassword1 = new javax.swing.JLabel();
        jLPassword2 = new javax.swing.JLabel();
        jBRegister = new javax.swing.JButton();
        jBBack = new javax.swing.JButton();
        jLUserError = new javax.swing.JLabel();
        jLPassword1Error = new javax.swing.JLabel();
        jLPassword2Error = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new Color(0,0,0,0));
        setForeground(new java.awt.Color(255, 0, 0));

        jTUserName.setText("Usuari");
        jTUserName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTUserNameMouseClicked(evt);
            }
        });

        jPassword1.setText("jPasswordField1");
        jPassword1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPassword1FocusGained(evt);
            }
        });
        jPassword1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPassword1KeyReleased(evt);
            }
        });

        jPassword2.setText("jPasswordField1");
        jPassword2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPassword2FocusGained(evt);
            }
        });
        jPassword2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPassword2KeyReleased(evt);
            }
        });

        jLUserName.setForeground(new java.awt.Color(255, 255, 255));
        jLUserName.setText("Usuari:");

        jLPassword1.setForeground(new java.awt.Color(255, 255, 255));
        jLPassword1.setText("Contrasenya:");

        jLPassword2.setForeground(new java.awt.Color(255, 255, 255));
        jLPassword2.setText("Repeteix contrasenya:");

        jBRegister.setText("OK");
        jBRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBRegisterMouseClicked(evt);
            }
        });

        jBBack.setText("ENRERE");
        jBBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBBackMouseClicked(evt);
            }
        });

        jLUserError.setForeground(new java.awt.Color(255, 0, 0));

        jLPassword1Error.setForeground(new java.awt.Color(255, 0, 0));

        jLPassword2Error.setForeground(new java.awt.Color(255, 0, 0));

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NOU USUARI");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 186, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLUserError, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLPassword1Error, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLPassword2Error, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBBack)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLPassword1)
                        .addComponent(jLPassword2)
                        .addComponent(jLUserName)))
                .addGap(186, 186, 186))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(jLUserName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLUserError, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLPassword1)
                .addGap(4, 4, 4)
                .addComponent(jPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLPassword1Error, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLPassword2)
                .addGap(2, 2, 2)
                .addComponent(jPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLPassword2Error, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBBack, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTUserNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTUserNameMouseClicked
        if (jTUserName.getText().equals("Usuari")) {
            jTUserName.setText("");
        }
    }//GEN-LAST:event_jTUserNameMouseClicked

    private void jBRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBRegisterMouseClicked
        this.register();
    }//GEN-LAST:event_jBRegisterMouseClicked

    private void jPassword2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPassword2KeyReleased
        if (correctPassword()) {
            setPassword2ErrorMesage("");
        } else {
            setPassword2ErrorMesage("Les contrasenyes no coincideixen");
        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.register();
        }
    }//GEN-LAST:event_jPassword2KeyReleased

    private void jPassword1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPassword1KeyReleased
        if (correctPassword()) {
            setPassword2ErrorMesage("");
        } else {
            setPassword2ErrorMesage("Les contrasenyes no coincideixen");
        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.register();
        }
    }//GEN-LAST:event_jPassword1KeyReleased

    private void jBBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBBackMouseClicked
        pCtrl.setPanel("login");
    }//GEN-LAST:event_jBBackMouseClicked

    private void jPassword1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPassword1FocusGained
        jPassword1.setText("");
    }//GEN-LAST:event_jPassword1FocusGained

    private void jPassword2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPassword2FocusGained
        jPassword2.setText("");
    }//GEN-LAST:event_jPassword2FocusGained

    private void register() {
        String user = this.getUsername();
        if (user == null) {
            this.setUserErrorMesage("El camp està buit.");
            return;
        }
        String pass1 = this.getPassword1();
        if (pass1 == null) {
            this.setPassword1ErrorMesage("El camp està buit.");
            return;
        }
        String pass2 = this.getPassword2();
        if (pass2 == null) {
            this.setPassword2ErrorMesage("El camp està buit.");
            return;
        }
        if (user.equals("Usuari")) {
            this.setUserErrorMesage("Nom per defecte no vàlid.");
            return;
        }
        if (!correctPassword()) {
            setPassword2ErrorMesage("Les contrasenyes no coincideixen.");
            return;
        }
        if (pass1.equals("jPasswordField1")) {
            setPassword2ErrorMesage("Contrasenyes per defecte no vàlides.");
            return;
        }
        if (uiCtrl.existsUsername(user)) {
            this.setUserErrorMesage("El nom d'usuari ja existeix.");
            return;
        }
        if (!uiCtrl.addUser(user, pass1)) {
            this.setUserErrorMesage("No s'ha pogut crear l'usuari. Error desconegut.");
        }
    }

    private String getUsername() {
        String user = jTUserName.getText();
        if ("".equals(user)) {
            return null;
        }
        return user;
    }

    private String getPassword1() {
        String pass = new String(jPassword1.getPassword());
        if ("".equals(pass)) {
            return null;
        }
        return pass;
    }

    private String getPassword2() {
        String pass = new String(jPassword2.getPassword());
        if ("".equals(pass)) {
            return null;
        }
        return pass;
    }

    /**
     * comprova que l'usuari sigui unic a la base de dades
     *
     * @return
     */
    private boolean correctUser() {
        // TODO mirar si l'usuari es unic a la base de dades
        return true;
    }

    /**
     * comprova que les 2 contraseñes son iguals
     *
     * @return
     */
    private boolean correctPassword() {
        return Arrays.toString(jPassword1.getPassword()).equals(Arrays.toString(jPassword2.getPassword()));
    }

    /**
     * Comprova que la informació del formulari sigui correcta
     *
     * @return
     */
    private boolean correctData() {
        return correctUser() && correctPassword();
    }

    /**
     * Retorna la informació del formulari en forma d'String
     *
     * @return
     */
    private String sendData() {
        return jTUserName.getText() + "," + Arrays.toString(jPassword1.getPassword());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBack;
    private javax.swing.JButton jBRegister;
    private javax.swing.JLabel jLPassword1;
    private javax.swing.JLabel jLPassword1Error;
    private javax.swing.JLabel jLPassword2;
    private javax.swing.JLabel jLPassword2Error;
    private javax.swing.JLabel jLUserError;
    private javax.swing.JLabel jLUserName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPassword1;
    private javax.swing.JPasswordField jPassword2;
    private javax.swing.JTextField jTUserName;
    // End of variables declaration//GEN-END:variables
}
