/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation.popups;

import controllers.presentation.EditorPresentationCtrl;
import controllers.presentation.PresentationCtrl;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author dani
 */
public class ChooseSize extends javax.swing.JPanel {

    /**
     * Controllers
     */
    private PresentationCtrl pCtrl;
    private EditorPresentationCtrl epCtrl;

    /**
     * Models
     */
    private DefaultComboBoxModel<Integer> dcbmSize;

    /**
     * Creates new form DeleteUserView
     * @param pCtrl controlador de presentació
     */
    public ChooseSize(PresentationCtrl pCtrl) {
        this.pCtrl = pCtrl;
        this.epCtrl = pCtrl.getEditorPresentationCtrl();
        initSizeModel();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlSize = new javax.swing.JLabel();
        jcbSize = new javax.swing.JComboBox();
        jbExit = new javax.swing.JButton();
        jbPlay = new javax.swing.JButton();
        jlTitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 153));

        jlSize.setFont(new java.awt.Font("Cantarell", 1, 20)); // NOI18N
        jlSize.setForeground(new java.awt.Color(16, 35, 235));
        jlSize.setText("Mida");

        jcbSize.setModel(dcbmSize);

        jbExit.setText("SORTIR");
        jbExit.setToolTipText("");
        jbExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExitActionPerformed(evt);
            }
        });

        jbPlay.setText("EDITAR");
        jbPlay.setToolTipText("");
        jbPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPlayActionPerformed(evt);
            }
        });

        jlTitle.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jlTitle.setText("EDITOR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlSize)
                                .addGap(59, 59, 59)
                                .addComponent(jcbSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jbExit, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                    .addComponent(jbPlay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jlTitle)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTitle)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSize, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jbPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbExit, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExitActionPerformed
        exitAction();
    }//GEN-LAST:event_jbExitActionPerformed

    private void jbPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPlayActionPerformed
        playAction();
    }//GEN-LAST:event_jbPlayActionPerformed

    private void playAction() {
        int n = (int) this.jcbSize.getSelectedItem();
        epCtrl.startEditor(n);
        pCtrl.setPopUpVisible(false);
        pCtrl.removeGlassPane();
    }

    private void exitAction() {
        pCtrl.setPopUpVisible(false);
        pCtrl.removeGlassPane();
    }

    private void initSizeModel() {
        Integer[] items = this.epCtrl.getSizeModel();
        this.dcbmSize = new DefaultComboBoxModel<>(items);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbExit;
    private javax.swing.JButton jbPlay;
    private javax.swing.JComboBox jcbSize;
    private javax.swing.JLabel jlSize;
    private javax.swing.JLabel jlTitle;
    // End of variables declaration//GEN-END:variables
}
