/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation.popups;

import controllers.presentation.GamePresentationCtrl;
import controllers.presentation.PresentationCtrl;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author dani
 */
public class ChooseRandom extends javax.swing.JPanel {

    /**
     * Controllers
     */
    private final PresentationCtrl pCtrl;
    private final GamePresentationCtrl gpCtrl;

    /**
     * Models
     */
    private DefaultComboBoxModel<Integer> dcbmSize;
    private DefaultComboBoxModel<String> dcbmDifficulty;
    private DefaultComboBoxModel<String> dcbmHelpLevel;

    /**
     * Creates new form DeleteUserView
     * @param pCtrl controlador de presentació
     */
    public ChooseRandom(PresentationCtrl pCtrl) {
        this.pCtrl = pCtrl;
        this.gpCtrl = pCtrl.getGamePresentationCtrl();
        initModels();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlSize = new javax.swing.JLabel();
        jcbSize = new javax.swing.JComboBox();
        jbExit = new javax.swing.JButton();
        jbPlay = new javax.swing.JButton();
        jlTitle = new javax.swing.JLabel();
        jlDifficulty = new javax.swing.JLabel();
        jcbDifficulty = new javax.swing.JComboBox();
        jlHelpLevel = new javax.swing.JLabel();
        jcbHelpLevel = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(153, 153, 153));

        jlSize.setFont(new java.awt.Font("Cantarell", 1, 20)); // NOI18N
        jlSize.setForeground(new java.awt.Color(16, 35, 235));
        jlSize.setText("Mida");

        jcbSize.setModel(dcbmSize);

        jbExit.setText("SORTIR");
        jbExit.setToolTipText("");
        jbExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExitActionPerformed(evt);
            }
        });

        jbPlay.setText("GENERAR");
        jbPlay.setToolTipText("");
        jbPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPlayActionPerformed(evt);
            }
        });

        jlTitle.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jlTitle.setText("ALEATORI");

        jlDifficulty.setFont(new java.awt.Font("Cantarell", 1, 20)); // NOI18N
        jlDifficulty.setForeground(new java.awt.Color(244, 26, 4));
        jlDifficulty.setText("Dificultat");

        jcbDifficulty.setModel(dcbmDifficulty);

        jlHelpLevel.setFont(new java.awt.Font("Cantarell", 1, 20)); // NOI18N
        jlHelpLevel.setForeground(new java.awt.Color(1, 160, 4));
        jlHelpLevel.setText("Nivell d'ajuda");

        jcbHelpLevel.setModel(dcbmHelpLevel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 180, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbSize, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbDifficulty, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbHelpLevel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbExit, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbPlay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlTitle)
                            .addComponent(jlHelpLevel)
                            .addComponent(jlSize)
                            .addComponent(jlDifficulty))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTitle)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSize, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDifficulty)
                    .addComponent(jcbDifficulty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlHelpLevel)
                    .addComponent(jcbHelpLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbExit, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExitActionPerformed
        exitAction();
    }//GEN-LAST:event_jbExitActionPerformed

    private void jbPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPlayActionPerformed
        playAction();
    }//GEN-LAST:event_jbPlayActionPerformed

    private void playAction() {
        int n = (int)this.jcbSize.getSelectedItem();
        String difficulty = this.gpCtrl.translateDifficulty((String)this.jcbDifficulty.getSelectedItem());
        String helpLevel = this.gpCtrl.translateHelpLevel((String)this.jcbHelpLevel.getSelectedItem());
        this.gpCtrl.startRandomGame(n, difficulty, helpLevel);
        pCtrl.setPopUpVisible(false);
        pCtrl.removeGlassPane();
    }

    private void exitAction() {
        pCtrl.setPopUpVisible(false);
        pCtrl.removeGlassPane();
    }

    private void initSizeModel() {
        Integer[] items = this.gpCtrl.getSizeModel();
        this.dcbmSize = new DefaultComboBoxModel<>(items);
    }

    private void initDifficultyModel() {
        String[] items = this.gpCtrl.getDifficultyModel();
        for (int i = 0; i < items.length; i++) {
            items[i] = this.gpCtrl.translateDifficulty(items[i]);
        }
        this.dcbmDifficulty = new DefaultComboBoxModel<>(items);
    }

    private void initHelpLevelModel() {
        String[] items = this.gpCtrl.getHelpLevelModel();
        for (int i = 0; i < items.length; i++) {
            items[i] = this.gpCtrl.translateHelpLevel(items[i]); 
        }
        this.dcbmHelpLevel = new DefaultComboBoxModel<>(items);
    }

    private void initModels() {
        initSizeModel();
        initDifficultyModel();
        initHelpLevelModel();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbExit;
    private javax.swing.JButton jbPlay;
    private javax.swing.JComboBox jcbDifficulty;
    private javax.swing.JComboBox jcbHelpLevel;
    private javax.swing.JComboBox jcbSize;
    private javax.swing.JLabel jlDifficulty;
    private javax.swing.JLabel jlHelpLevel;
    private javax.swing.JLabel jlSize;
    private javax.swing.JLabel jlTitle;
    // End of variables declaration//GEN-END:variables
}
