/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation.popups;

import controllers.domain.UserDomainCtrl;
import controllers.presentation.PresentationCtrl;
import controllers.presentation.UserPresentationCtrl;
import java.awt.Color;

/**
 *
 * @author Ferran
 */
public class DeleteUser extends javax.swing.JPanel {
    
    PresentationCtrl pCtrl;
    UserPresentationCtrl uCtrl;
    UserDomainCtrl uDCtrl;
    /**
     * Creates new form DeleteUserView
     * @param pCtrl controlador de presentació
     */
    public DeleteUser(PresentationCtrl pCtrl) {
        this.pCtrl = pCtrl;
        this.uCtrl = pCtrl.getUserPresentationCtrl();
        this.uDCtrl = pCtrl.getUserDomainCtrl();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jYes = new javax.swing.JButton();
        jNo = new javax.swing.JButton();
        jPasswordLabel = new javax.swing.JLabel();
        jWarningLabe = new javax.swing.JLabel();
        jMessageLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 153));

        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField1MouseClicked(evt);
            }
        });
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        jYes.setText("Esborrar Usuari");
        jYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jYesActionPerformed(evt);
            }
        });

        jNo.setText("Cancel·la");
        jNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNoActionPerformed(evt);
            }
        });

        jPasswordLabel.setText("Contrasenya:");

        jWarningLabe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/warning30x30.png"))); // NOI18N

        jMessageLabel.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        jMessageLabel.setText("Vols eliminar el teu usuari?");

        jLabel1.setBackground(new Color(0,0,0,0));
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jWarningLabe)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jMessageLabel)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jNo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(jYes)))
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jMessageLabel)
                    .addComponent(jWarningLabe, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jPasswordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jYes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jYesActionPerformed
        String password = getPassword();
        String user = uCtrl.getUsername();
        if (uDCtrl.correctLoginUser(user, password)) {
            uCtrl.logout();
            uCtrl.deleteUser(user, password);
            pCtrl.setPopUpVisible(false);
            pCtrl.setPanel("login");
        }
        else {
            setErrorMessage("Contrasenya incorrecta");
        }
    }//GEN-LAST:event_jYesActionPerformed

    private void jNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNoActionPerformed
        pCtrl.setPopUpVisible(false);
    }//GEN-LAST:event_jNoActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jPasswordField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MouseClicked
        jPasswordField1.setText("");
    }//GEN-LAST:event_jPasswordField1MouseClicked

    private String getPassword() {
        return new String(jPasswordField1.getPassword());
    }
    
    public void setErrorMessage(String s){
        jLabel1.setText(s);
        pCtrl.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jMessageLabel;
    private javax.swing.JButton jNo;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel jPasswordLabel;
    private javax.swing.JLabel jWarningLabe;
    private javax.swing.JButton jYes;
    // End of variables declaration//GEN-END:variables
}
