/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation.popups;

import controllers.presentation.PresentationCtrl;

/**
 *
 * @author Marc
 */
public class FinishGame extends javax.swing.JPanel {
    PresentationCtrl presentationCtrl;
    /**
     * Creates new form FinalGame
     * @param presentationCtrl controlador de presentació
     */
    public FinishGame(PresentationCtrl presentationCtrl) {
        this.presentationCtrl = presentationCtrl;
        initComponents();
    }
    
    public void getScore() {
        int score = this.presentationCtrl.getGamePresentationCtrl().getScore();
        this.jlScoreValue.setText(Integer.toString(score));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        congratulations = new javax.swing.JLabel();
        menu = new javax.swing.JButton();
        jlScoreName = new javax.swing.JLabel();
        jlScoreValue = new javax.swing.JLabel();

        congratulations.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        congratulations.setText("Felicitats!");

        menu.setText("TORNAR AL MENU");
        menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMouseClicked(evt);
            }
        });

        jlScoreName.setText("Puntuació:");

        jlScoreValue.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(congratulations, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlScoreName)
                        .addGap(18, 18, 18)
                        .addComponent(jlScoreValue))
                    .addComponent(menu))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(congratulations, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlScoreName)
                    .addComponent(jlScoreValue))
                .addGap(20, 20, 20)
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseClicked
        getScore();
        presentationCtrl.setPopUpVisible(false);
        presentationCtrl.removeGlassPane();
        presentationCtrl.setPanel("home");
    }//GEN-LAST:event_menuMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel congratulations;
    private javax.swing.JLabel jlScoreName;
    private javax.swing.JLabel jlScoreValue;
    private javax.swing.JButton menu;
    // End of variables declaration//GEN-END:variables
}
